package types

var FileFormats = map[string]FileFormat{
	"txt": {FormatName: "txt",
		Description: "Text file",
		Validator:   func(d Data) bool { return true }},
	"vw": {FormatName: "vw",
		Description: "Vowpal Wabbit input file",
		Validator:   func(d Data) bool { return true }},
	"csv": {FormatName: "csv",
		Description: "Comma separated values, without a header",
		Validator:   func(d Data) bool { return true }},
	"tsv": {FormatName: "tsv",
		Description: "Tab separated values, without a header",
		Validator:   func(d Data) bool { return true }},
	"libsvm": {FormatName: "libsvm",
		Description: "libSVM format file",
		Validator:   func(d Data) bool { return true }},
	"npy": {FormatName: "npy",
		Description: "Memory mapped numpy array",
		Validator:   func(d Data) bool { return true }},
	"h5": {FormatName: "h5",
		Description: "Hierarchical Data Format 5 (HDF5)",
		Validator:   func(d Data) bool { return true }},
	"rda": {FormatName: "rda",
		Description: "R data",
		Validator:   func(d Data) bool { return true }},
	"dat": {FormatName: "dat",
		Description: "Matlab data format",
		Validator:   func(d Data) bool { return true }},
	"arff": {FormatName: "arff",
		Description: "Weka format",
		Validator:   func(d Data) bool { return true }},
}
